Preliminary implementation of model store and retrieve
wasmCloud/wadm pull request #18
Opened 2022-06-10 11:45 UTC by autodidaddict

Initial implementation of CRUD functionality on app specs. Also implements deploy/undeploy functionality on the agent process, though the agent process currently does nothing.

2022-06-10 20:12 UTC, connorsmith256 approved these changes

2022-06-10 20:12 UTC, connorsmith256 commented on wadm/lib/wadm/model/store.ex
> +  def lattice_models(redis, lattice_id) when is_binary(lattice_id) do
This could use a doc indicating it returns the most recent version for each model

2022-06-13 16:52 UTC, thomastaylor312 requested changes
One super minor change and a few nits

2022-06-13 16:52 UTC, thomastaylor312 commented on wadm/lib/supervisor.ex
> +        {Redix, host: System.get_env("REDIS_HOST") || "127.0.0.1", name: :model_store},
Nit: Should probably be `WADM_REDIS_HOST`

2022-06-13 16:52 UTC, thomastaylor312 commented on wadm/lib/wadm/model/store.ex
> +      dt |> DateTime.to_iso8601()
So this goes to iso8601 and not rfc3339. They are basically the same, but as far as I understand the `T` separator is the main difference. I don't care which one we use, but we should make sure it is the right format

2022-06-13 16:58 UTC, autodidaddict commented on wadm/lib/wadm/api/api_server.ex
> +  # Versions will be returned in order of newest-first
this comes from the timestamp of the revision being the score in the scored set. when we do `REV` on the output, we get it in descending order.

2022-06-18 16:54 UTC, autodidaddict commented on wadm/lib/wadm/model/store.ex
> +  def delete_model_version(redis, model_name, version, lattice_id)
need to drop the model name. Good catch

2022-06-18 17:16 UTC, merged