Added WIT bindings for OAM types and subscription method
wasmCloud/wadm pull request #301
Opened 2024-06-08 17:15 UTC by LUK3ARK

Here I add all bindings for wit generated OAM types and binds them to be translated to and from with the rust types already defined.

I also add a subscribe method which allows the subscription to wadm status api through the client.

NOTE: previously this subscription relied on wrpc and provider specific implementations. I chose to implement as mpsc to keep the wadm client as a thin agnostic wrapper where we can use in multiple streaming scenarios whether that is in CLI, providers, etc. 

Let me know if anyone has any improvements or ideas

2024-06-10 13:48 UTC, LUK3ARK commented
Where is best to keep the WIT for this? Should we just add release to this repo or the main wasmcloud repo? 
The deps.toml file of the wadm provider in the wasmcloud repo will need to be adjusted to reflect this.

2024-06-11 22:48 UTC, thomastaylor312 commented
@LUK3ARK I think the wit would belong here for now I think for discoverability. We'd need to add a build for packaging up the wit like the one found [here](https://github.com/wasmCloud/wasmCloud/blob/main/.github/workflows/wash-plugins.yml). In the next few months we'll covert it to be stored in OCI, but for now, this would allow it to integrate in with the current flow

2024-06-11 23:00 UTC, thomastaylor312 requested changes
This is really great! And thanks for the bonus status streaming stuff. Added a few comments for addressing

2024-06-11 23:06 UTC, thomastaylor312 commented on wit/wadm/client.wit
> +    delete-model-version: func(model-name: string, version: option<string>, delete-all: bool, lattice: option<string>) -> result<bool, string>;
Oh heads up that the signature for this now should drop `delete-all` as that is now the default behavior. Everything else can stay the same

2024-06-26 15:29 UTC, LUK3ARK commented on wit/oam/oam.wit
> +package wasmcloud:oam@0.1.0;
i just put everything in wadm this good?

2024-06-26 20:30 UTC, thomastaylor312 commented on wit/wadm/client.wit
> +    use wasmcloud:oam/types@0.1.0.{oam-manifest};
Looks like you did end up combining the oam stuff into wadm types, so should this be removed from the wit files?

2024-06-26 20:30 UTC, thomastaylor312 commented on wit/oam/oam.wit
> +package wasmcloud:oam@0.1.0;
Yep, you're good!

2024-07-01 14:57 UTC, thomastaylor312 approved these changes

2024-07-01 14:57 UTC, thomastaylor312 commented
@LUK3ARK good to go pending a quick rebase!

2024-07-02 15:01 UTC, thomastaylor312 approved these changes

2024-07-02 20:05 UTC, brooksmtownsend approved these changes
🚀 @LUK3ARK looks like this branch just might have some conflicts to resolve and otherwise g2g

2024-07-12 15:45 UTC, brooksmtownsend commented
Rebasing...

2024-07-12 15:52 UTC, merged