allow unique interfaces across duplicate links and test
wasmCloud/wadm pull request #518
Opened 2024-12-14 13:11 UTC by LUK3ARK

Related fix for https://github.com/wasmCloud/wasmCloud/issues/3801

2024-12-14 13:12 UTC, LUK3ARK commented
I didn't see any changes in WADM required, seems that it treats each interface explicitly anyway. Let me know if I have missed anything other than this validation level.

2024-12-19 14:07 UTC, brooksmtownsend requested changes
This all looks great, we should just hold it back until wasmCloud supports this same matching validation

2024-12-29 23:58 UTC, LUK3ARK commented
What are we still waiting for with this? Major blocker for me at the moment

2024-12-31 16:12 UTC, brooksmtownsend approved these changes

2024-12-31 16:12 UTC, merged