Wadm 0.4 Release Workflow Update
wasmCloud/wadm pull request #82
Opened 2023-04-13 15:35 UTC by stephenandary

## Feature or Problem

## Related Issues

## Release Information

## Consumer Impact

## Testing

Built on platform(s)
- [x] x86_64-linux
- [x] aarch64-linux
- [x] x86_64-darwin
- [x] aarch64-darwin
- [x] x86_64-windows

Tested on platform(s)
- [ ] x86_64-linux
- [ ] aarch64-linux
- [ ] x86_64-darwin
- [ ] aarch64-darwin
- [ ] x86_64-windows

### Unit Test(s)

### Acceptance or Integration

### Manual Verification

2023-04-14 15:40 UTC, stephenandary commented on .github/workflows/release.yml
> +          rustup toolchain install stable-aarch64-unknown-linux-gnu
I have tried to condense this step with the following "Install Rust Stable Toolchain Step", however, it does not work. Not really sure why, and don't want to spend much more time on this. I have tried changing step order as well. For now this works, but it seems redundant to have this step. May be nice to condense in future.

2023-04-14 15:41 UTC, stephenandary commented
I have removed steps related to actions-rs in the workflow, as actions-rs is no longer maintained. For toolchain installation, I have switched to Dtolnay/Toolchain and for actions-rs/cargo I am just now running cargo commands with `run:`

2023-04-14 22:01 UTC, stephenandary commented
Nothing has been tested yet, but the PR is at a good point now to come out of Draft to discuss.

2023-04-15 20:39 UTC, thomastaylor312 requested changes

2023-04-15 20:39 UTC, thomastaylor312 commented on .github/workflows/release.yml
> +      - "canary"
By default a push to main should be `canary` and just overwrite the current version. That is basically what you have below, but we aren't planning on pushing just a plain canary tag

2023-04-15 20:39 UTC, thomastaylor312 commented on .github/workflows/release.yml
> +      - name: set the release version (manually trigger test with canary tag push)
If you want to keep this around, you can just have a workflow trigger

2023-04-15 20:39 UTC, thomastaylor312 commented on Dockerfile
> +CMD ["/usr/local/bin/wadm"]
Can you change this to be `ENTRYPOINT` so that people can pass args to the container?

2023-04-16 21:50 UTC, thomastaylor312 approved these changes

2023-04-16 21:51 UTC, thomastaylor312 commented
Great work here @stephenandary!

2023-04-16 21:52 UTC, thomastaylor312 commented
Also, please note that this will not run until we merge `wadm_0.4` into `main` and that is fine

2023-04-16 21:54 UTC, merged